<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <AssemblyName>CruSplitProbe</AssemblyName>
    <AOSharpDir Condition="'$(AOSharpDir)' == ''">$(MSBuildThisFileDirectory)lib</AOSharpDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AOSharp.Core">
      <HintPath>$(AOSharpDir)/AOSharp.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AOSharp.Common">
      <HintPath>$(AOSharpDir)/AOSharp.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
